# Generated by Django 4.1.7 on 2023-05-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_evento_premiacao', '0002_rename_numero_registro_avaliador_avaliador_numero_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto_avaliado',
            name='nota',
            field=models.FloatField(),
        ),
    ]
